spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
         - id: user-profile
           uri: lb://user-profile
           predicates:
            - Path=/users/**
           filters:
             - AuthenticationFilter

         - id: auth-service
           uri: lb://auth-service
           predicates:
             - Path=/auth/**
           filters:
           - AuthenticationFilter

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

