spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


