spring:
  application:
    name: user-profile
  datasource:
    url: jdbc:postgresql://localhost:5432/user_profile
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  cache:
    type: redis
    cache-names:
      - address
      - account
      - employment-record
    redis:
      cache-null-values: false
      time-to-live: 86400000
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
