spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
         - id: user-profile
           uri: lb://user-profile
           predicates:
            - Path=/users/**
           filters:
             - AuthenticationFilter

         - id: auth-service
           uri: lb://auth-service
           predicates:
             - Path=/auth/**
           filters:
           - AuthenticationFilter

         - id: loan-service
           uri: lb://loan-service
           predicates:
             - Path=/loan/**
           filters:
             - AuthenticationFilter
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

